services:
  app:
    image: zaivod-logistics-app
    build: .
    restart: unless-stopped
    env_file: .env
    ports: 
      - 8080:8080
#     networks:
#       - reverse-proxy_net
# networks:
#   reverse-proxy_net:
#     external: true
